quarkus.http.port=8081
%test.quarkus.temporal.enable-mock=true
# note: can't automatically start workers if you need to register mocked activities
%test.quarkus.temporal.start-workers=false
quarkus.grpc.server.use-separate-server=false

# Duration of 5 Minutes using Duration.parse
order-entity-polling-rate=${ORDER_ENTITY_POLLING_RATE:PT5M}
# Duration of 10 Minutes using Duration.parse
order-expiry-duration=${ORDER_EXPIRY_DURATION:PT8M}

quarkus.temporal.namespace=default
quarkus.temporal.worker.task-queue=${ORDER_ENTITY_TASKS:order-entity-tasks}
quarkus.temporal.worker."cas-rate-limited".task-queue=cas-rate-limited-tasks
